# netlify.toml for API

[build]
  command = "yarn build"
  publish = "packages/api/dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  PORT = "3000"

[[functions]]
  directory = "packages/api/dist"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/api"
  status = 200