[build]
  base = "packages/ui"
  command = "yarn install && yarn build"
  publish = "packages/ui/.next"
  functions = "packages/ui/netlify/functions"

[build.environment]
  NODE_VERSION = "16.14.0"  # or whichever version you're using
