# Version of the configuration file
version = "3"

[build]
  # Root directory of the project
  command = "yarn build"
  publish = "packages/ui/build" # Adjust based on the UI build output directory

# Deploying the API as a serverless function
[[functions]]
  # API endpoint configuration
  directory = "packages/api/functions" # Adjust based on the serverless function directory

[[plugins]]
  package = "@netlify/plugin-docker"

# Environment variables for both UI and API
[context.production.environment]
  NODE_ENV = "production"
  API_URL = "/.netlify/functions/api" # Proxying API through Netlify functions
  REDIS_URL = "your-redis-connection-url"
  DATABASE_URL = "your-postgres-connection-url"

# Redirects for API and UI
[[redirects]]
  # Proxy requests to the API function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  # Serve UI from the root
  from = "/*"
  to = "/index.html"
  status = 200