# netlify.toml for API

[build]
  command = "yarn build"
  publish = "packages/api/dist"
  base = "/"

[functions]
  directory = "packages/api/dist"

[build.environment]
  NODE_VERSION = "16"
  PORT = "3000"

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/api"
  status = 200