[build]
  base = "packages/ui" 
  publish = "packages/ui/out" 
  command = "yarn install && yarn build" 
[build.environment]
  NODE_VERSION = "16.14.0"

[functions]
  directory = "netlify/functions" 

[dev]
  command = "yarn bootstrap && yarn dev"
